name: Android CI
on: [pull_request]

jobs:
  Build-UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew assembleDebug testDebugUnitTest
  ktlintCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew ktlintCheck
  Espresso:
    runs-on: macOS-latest
    strategy:
      matrix:
        api: [21, 28]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Android Emulator test ${{ matrix.api }}
        uses: ReactiveCircus/android-emulator-runner@v2.8.0
        with:
          api-level: ${{ matrix.api }}
          disable-animations: true
          script: ./gradlew cAT
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Espresso-test-report
          path: mail/common/build/reports/androidTests/connected/
